
#pragma once

#include <Windows.h>

HANDLE consoleHandle;

#define COLOUR_DEFAULT FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
#define COLOUR_PLR1 BACKGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY
#define COLOUR_PLR2 BACKGROUND_BLUE | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY

